Repository SimonStnn/pop-a-loon, pull requests merged in 2024-02, with the labels that each got.

#14 Move to react
  package-lock.json
  package.json
  src/background/background.ts
  src/components/NavigationIcon.tsx
  src/const.ts
  src/popup/App.tsx
  src/popup/Settings.tsx
  src/popup/index.html
  src/popup/index.tsx
  src/popup/popup.ts
  src/popup/style.css
  tsconfig.json
  webpack.config.js
Labels: enhancement

#15 Use tailwindcss for styling
  manifest.json
  package-lock.json
  package.json
  postcss.config.js
  prettier.config.js
  src/components/NavigationIcon.tsx
  src/popup/App.tsx
  src/popup/Settings.tsx
  src/popup/index.tsx
  src/popup/style.css
  src/utils.ts
  tailwind.config.js
  webpack.config.js
Labels: enhancement

#16 Add pre-commit hook with prettier
  .husky/pre-commit
  .prettierrc
  package-lock.json
  package.json
  prettier.config.js
  src/popup/App.tsx
Labels: enhancement

#17 Remove unnecessary permissions from manifest.json
  manifest.json
Labels: bug

#18 Update version to 1.3.2 in manifest and package files
  manifest.json
  package-lock.json
  package.json
Labels: documentation

#22 Add chrome web store version badge to readme
  README.md
  manifest.json
  package-lock.json
  package.json
Labels: documentation

#24 Reset counter when count is undefined close #23
  manifest.json
  package-lock.json
  package.json
  src/background/background.ts
Labels: bug

#26 Update store id close #25
  README.md
Labels: bug

#28 Add background color to body
  src/popup/index.html
Labels: bug

#31 Add screenshot to README
  README.md
  manifest.json
  resources/images/Screenshot-1.png
  resources/images/icon.png
  src/const.ts
Labels: documentation, enhancement

#36 Feature/badge number abbreviation
  package-lock.json
  package.json
  src/background/background.ts
Labels: enhancement

#37 Set badge gb and text color close #32
  src/background/background.ts
Labels: enhancement
